# Generated by Django 4.2.11 on 2024-03-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mydashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrecord',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='clientrecord',
            name='longitude',
        ),
    ]
